Repository loomi-dev/bayer-geracao-demanda-client, pull requests merged in 2023-12, with the labels that each got.

#39 Feat/wallet page api
  package.json
  src/api/types.ts
  src/modules/wallet/api/endpoints.ts
  src/modules/wallet/api/queries/index.ts
  src/modules/wallet/api/queries/useGetFaqs.ts
  src/modules/wallet/api/queries/useGetFarmers.ts
  src/modules/wallet/api/types.ts
  src/modules/wallet/index.ts
  src/modules/wallet/pages/WalletScreen/components/Balance.tsx
  src/modules/wallet/pages/WalletScreen/components/Faq.tsx
  src/utils/formatPrice.ts
  src/utils/index.ts
  yarn.lock
Labels: Feature

#40 Feat/customers page table
  src/components/BaseFilter/components/FilterTrigger.tsx
  src/components/filters/PartnerFilter/PartnerFilter.tsx
  src/components/filters/PartnerFilter/index.ts
  src/components/filters/index.ts
  src/modules/customers/pages/CustomersScreen/CustomersScreen.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerTable.columns.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerTable.tsx
  src/modules/customers/pages/CustomersScreen/components/index.tsx
  src/styles/theme/foundations/textStyles.ts
Labels: Feature

#41 Feat/register flow
  package.json
  public/assets/icons/ArrowRightMediumIcon.svg
  public/assets/icons/ArrowRightSmallIcon.svg
  public/assets/icons/BusinessIcon.svg
  public/assets/icons/EmailIcon.svg
  src/api/auth/endpoints.ts
  src/api/auth/mutations/index.ts
  src/api/auth/mutations/useUpdateUser.ts
  src/api/auth/types.ts
  src/components/PasswordInput/PasswordInput.tsx
  src/components/icons/ArrowRightMediumIcon.tsx
  src/components/icons/ArrowRightSmallIcon.tsx
  src/components/icons/BusinessIcon.tsx
  src/components/icons/EmailIcon.tsx
  src/components/icons/index.ts
  src/lib/next-auth/authOptions.ts
  src/lib/next-auth/providers/credentials.ts
  src/middleware.ts
  src/modules/auth/pages/OnboardingScreen/OnboardingScreen.tsx
  src/modules/auth/pages/RegisterScreen/RegisterScreen.tsx
  src/modules/auth/pages/RegisterScreen/components/RegisterFormTabs/AccountDataForm.tsx
  src/modules/auth/pages/RegisterScreen/components/RegisterFormTabs/CreatePasswordForm.tsx
  src/modules/auth/pages/RegisterScreen/components/RegisterFormTabs/PrivacyPoliciesModal.tsx
  src/modules/auth/pages/RegisterScreen/components/RegisterFormTabs/RegisterFormTabs.tsx
  src/modules/auth/pages/RegisterScreen/components/RegisterFormTabs/index.ts
  src/modules/auth/pages/RegisterScreen/components/RegisterFormTabs/registerFormTabs.schemas.ts
  src/modules/auth/pages/RegisterScreen/components/RegisterOverlay/RegisterOverlay.tsx
  src/modules/auth/pages/RegisterScreen/components/RegisterOverlay/index.ts
  src/modules/auth/pages/RegisterScreen/components/index.ts
  src/modules/auth/pages/RegisterScreen/stores/index.ts
  src/modules/auth/pages/RegisterScreen/stores/useRegisterFormTabs.ts
  src/styles/theme/components/input.ts
  src/styles/theme/foundations/semanticTokens.ts
  src/types/next-auth.d.ts
  yarn.lock
Labels: Feature

#44 feat: layout page planning
  public/assets/icons/BigCalendarIcon.svg
  public/assets/icons/Eye.svg
  public/assets/icons/EyeOff.svg
  public/assets/icons/Filter.svg
  public/assets/icons/Sliders.svg
  src/components/DynamicTable/DynamicTable.tsx
  src/components/PasswordInput/PasswordInput.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/icons/BigCalendarIcon.tsx
  src/components/icons/index.ts
  src/modules/planning/pages/PlanningScreen/PlanningScreen.tsx
  src/modules/planning/pages/components/BalanceSection/BalanceSection.tsx
  src/modules/planning/pages/components/BalanceSection/index.ts
  src/modules/planning/pages/components/PlanningTable/PlanningTable.tsx
  src/modules/planning/pages/components/PlanningTable/index.ts
  src/modules/planning/pages/components/PlanningTable/planningTable.columns.tsx
  src/modules/planning/pages/components/StatisticsSection/StatCard.tsx
  src/modules/planning/pages/components/StatisticsSection/StatisticsSection.tsx
  src/modules/planning/pages/components/StatisticsSection/index.ts
  src/modules/planning/pages/components/index.ts
  src/pages/planejamento/index.tsx
  src/styles/theme/foundations/layerStyles.ts
Labels: Feature

#46 Creates badge componetn
  src/styles/theme/components/badge.ts
  src/styles/theme/foundations/colors.ts
  src/styles/theme/foundations/semanticTokens.ts
Labels: Feature

#43 Feat/wallet page skeleton
  src/modules/wallet/pages/WalletScreen/components/Balance.tsx
  src/modules/wallet/pages/WalletScreen/components/Faq.tsx
  src/modules/wallet/pages/WalletScreen/components/Faq/Faq.tsx
  src/modules/wallet/pages/WalletScreen/components/Faq/FaqSkeleton.tsx
  src/modules/wallet/pages/WalletScreen/components/Faq/index.ts
  src/modules/wallet/pages/WalletScreen/components/Resources/Card.tsx
  src/modules/wallet/pages/WalletScreen/components/Resources/Resources.tsx
  src/styles/theme/components/index.ts
  src/styles/theme/components/skeleton.ts
Labels: Feature

#48 Feat/table pagination
  .github/pull_request_template.md
  public/assets/icons/ChevronLeftIcon.svg
  public/assets/icons/ChevronRightIcon.svg
  src/components/DynamicTable/DynamicTable.tsx
  src/components/DynamicTable/TableBodySkeleton.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/index.ts
  src/components/icons/ChevronLeftIcon.tsx
  src/components/icons/ChevronRightIcon.tsx
  src/components/icons/index.ts
  src/components/index.ts
  src/hooks/index.ts
  src/hooks/usePagination.tsx
  src/styles/theme/components/button.ts
Labels: Feature

#47 Feat/planning integration with api
  package.json
  src/api/farmer/endpoints.ts
  src/api/farmer/index.ts
  src/api/farmer/queries/index.ts
  src/api/farmer/queries/useGetFarmer.ts
  src/api/farmer/types.ts
  src/api/index.ts
  src/lib/authorization/Authorization.tsx
  src/lib/authorization/index.tsx
  src/lib/authorization/permissions/policies.ts
  src/lib/authorization/permissions/roles.ts
  src/lib/authorization/types.ts
  src/lib/authorization/usePBAC.tsx
  src/lib/authorization/useRBAC.tsx
  src/lib/axios.ts
  src/modules/planning/api/endpoints.ts
  src/modules/planning/api/index.ts
  src/modules/planning/api/queries/index.ts
  src/modules/planning/api/queries/useGetFarmerPlans.ts
  src/modules/planning/api/queries/useGetPlanningStatistics.ts
  src/modules/planning/api/types.ts
  src/modules/planning/pages/PlanningScreen/PlanningScreen.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningStatisticsSection/PlanningStatisticsSection.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningStatisticsSection/index.ts
  src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningBudgetColumn.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningStatusColumn.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTable.columns.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTable.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningTable/index.ts
  src/modules/planning/pages/PlanningScreen/components/index.ts
  src/modules/planning/pages/components/BalanceSection/BalanceSection.tsx
  src/modules/planning/pages/components/PlanningTable/PlanningTable.tsx
  src/modules/planning/pages/components/PlanningTable/planningTable.columns.tsx
  src/modules/planning/pages/components/StatCard/StatCard.tsx
  src/modules/planning/pages/components/StatCard/index.ts
  src/modules/planning/pages/components/StatisticsSection/StatCard.tsx
  src/modules/planning/pages/components/StatisticsSection/StatisticsSection.tsx
  src/modules/planning/pages/components/StatisticsSection/index.ts
  src/modules/planning/pages/components/index.ts
  src/modules/wallet/api/endpoints.ts
  src/modules/wallet/api/queries/index.ts
  src/modules/wallet/api/queries/useGetFarmers.ts
  src/modules/wallet/api/types.ts
  src/modules/wallet/pages/WalletScreen/components/Balance.tsx
  src/pages/_app.tsx
  src/styles/theme/components/button.ts
  src/styles/theme/foundations/semanticTokens.ts
  src/types/global.d.ts
  src/types/index.ts
  src/types/next-auth.d.ts
  src/utils/centsToCompactValue.ts
  src/utils/centsToInteger.ts
  src/utils/formatDate.ts
  src/utils/getTotalPlanningBudgetValue.ts
  src/utils/index.ts
  src/utils/numberToCompactValue.ts
  yarn.lock
Labels: Feature

#50 Adds deadline to balance
  src/api/farmer/endpoints.ts
  src/modules/wallet/pages/WalletScreen/components/Balance.tsx
Labels: Feature

#54 Feat/customer page api
  package.json
  src/api/customer/endpoints.ts
  src/api/customer/index.ts
  src/api/customer/queries/index.ts
  src/api/customer/queries/useGetCustomers.ts
  src/api/customer/types.ts
  src/api/index.ts
  src/api/manager/endpoints.ts
  src/api/manager/index.ts
  src/api/manager/queries/index.ts
  src/api/manager/queries/useGetManager.ts
  src/api/manager/types.ts
  src/api/types.ts
  src/config/index.ts
  src/modules/customers/pages/CustomersScreen/components/CustomerCards.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerCards/CustomerCards.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerCards/index.ts
  src/modules/customers/pages/CustomersScreen/components/CustomerTable.columns.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerTable.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.columns.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerTable/index.ts
  src/modules/wallet/api/types.ts
  src/types/global.d.ts
  src/utils/formatPrice.ts
  yarn.lock
Labels: Feature

#53 feat: new variant table
  src/components/DynamicTable/DynamicTable.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTable.columns.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTable.tsx
  src/styles/theme/components/table.ts
Labels: Feature

#49 feat: mask to identifier input
  src/components/TextInput/TextInput.tsx
  src/modules/auth/pages/LoginScreen/components/LoginForm/LoginForm.tsx
  src/utils/mask.ts
Labels: Feature

#58 Feat/customer detail page table
  src/api/index.ts
  src/api/planning/endpoints.ts
  src/api/planning/index.ts
  src/api/planning/mutations/index.ts
  src/api/planning/mutations/useCreatePlanning.ts
  src/api/planning/queries/index.ts
  src/api/planning/queries/useGetFarmerPlans.ts
  src/api/planning/queries/useGetPlanningActions.ts
  src/api/planning/queries/useGetPlanningActionsStatistics.ts
  src/api/planning/queries/useGetPlanningStatistics.ts
  src/api/planning/types.ts
  src/modules/customers/pages/CustomerDetailScreen/CustomerDetailScreen.tsx
  src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPendingPlanningNotification.tsx
  src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPlanningBudgetColumn.tsx
  src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPlanningStatusColumn.tsx
  src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPlanningTable.columns.tsx
  src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPlanningTable.tsx
  src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/index.ts
  src/modules/customers/pages/CustomerDetailScreen/components/index.ts
  src/modules/planning/components/StatCard/StatCard.tsx
  src/modules/planning/components/StatCard/index.ts
  src/modules/planning/components/index.ts
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsStatistics/PlanningActionsStatistics.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTable.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningBalance/PlanningBalance.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningStatisticsSection/PlanningStatisticsSection.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTable.tsx
  src/types/global.d.ts
Labels: Feature

#59 fix: payload update user, hover buttons, new component modal
  src/api/auth/endpoints.ts
  src/api/auth/mutations/useUpdateUser.ts
  src/api/auth/types.ts
  src/middleware.ts
  src/modules/auth/pages/LoginScreen/LoginScreen.tsx
  src/modules/auth/pages/LoginScreen/components/LoginForm/loginForm.schema.ts
  src/modules/auth/pages/RegisterScreen/components/RegisterFormTabs/PrivacyPoliciesModal.tsx
  src/modules/auth/pages/RegisterScreen/components/RegisterFormTabs/RegisterFormTabs.tsx
  src/pages/entrar/index.tsx
  src/styles/theme/components/button.ts
  src/styles/theme/components/modal.ts
  src/styles/theme/foundations/semanticTokens.ts
Labels: Fix

#60 Fix customers columns data display
  src/api/customer/endpoints.ts
  src/api/customer/types.ts
  src/components/icons/Clock.tsx
  src/components/icons/index.ts
  src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.columns.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTableStatusColumn.tsx
Labels: Feature

#61 feat: conditional to decrease or increment pages
  src/api/planning/endpoints.ts
  src/api/planning/types.ts
  src/components/DynamicTable/DynamicTable.tsx
  src/components/Pagination/Pagination.tsx
  src/hooks/usePagination.tsx
  src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPlanningTable.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTable.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTable.tsx
Labels: Feature

#66 Feat/drawer create planning action
  public/assets/icons/ArrowRightMediumIcon.svg
  public/assets/icons/ArrowRightSmallIcon.svg
  public/assets/icons/BigCalendarIcon.svg
  public/assets/icons/BusinessIcon.svg
  public/assets/icons/ChevronLeftIcon.svg
  public/assets/icons/ChevronRightIcon.svg
  public/assets/icons/EmailIcon.svg
  public/assets/icons/ExpandIcon.svg
  public/assets/icons/MinusIcon.svg
  src/components/SelectInput/SelectInput.tsx
  src/components/SelectInput/index.ts
  src/components/icons/DocumentIcon.tsx
  src/components/icons/ExpandIcon.tsx
  src/components/icons/MinusIcon.tsx
  src/components/icons/index.ts
  src/components/index.ts
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/AccordionIcon.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/CreatePlanningActionDrawerButton.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/PlanningActionForm.schema.ts
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/PlanningActionFormAccordion.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/PlanningActionFormStepper.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/RecommendationsAccordion.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/SelectDateSection.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/index.ts
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningBalance/CreatePlanningBalance.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionDetail/DetailItem.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionDetail/PlanningActionDetail.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionDetail/index.ts
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTable.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/index.ts
  src/modules/planning/pages/CreatePlanningScreen/stores/index.ts
  src/modules/planning/pages/CreatePlanningScreen/stores/useCreatePlanningActionStore.ts
  src/styles/theme/components/accordion.ts
  src/styles/theme/components/drawer.ts
  src/styles/theme/components/index.ts
  src/styles/theme/components/select.ts
  src/styles/theme/components/stepper.ts
  src/styles/theme/foundations/colors.ts
  src/styles/theme/foundations/semanticTokens.ts
Labels: Feature

#62 Creates customer planning detail layout
  src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPlanningTable.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/CustomerPlanningDetailScreen.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/index.ts
  src/modules/customers/pages/index.ts
  src/pages/clientes/[customer_id]/detalhes/[planning_id].tsx
  src/pages/clientes/[customer_id]/index.tsx
Labels: Feature

#63 Feat/customer planning details cards
  src/api/auth/types.ts
  src/api/farmer/endpoints.ts
  src/components/Balance/BalanceExpirationDate.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/CustomerPlanningDetailScreen.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningDetailCards/CustomerPlanningDetailCards.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningDetailCards/index.ts
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/index.ts
  src/types/global.d.ts
Labels: Feature

#67 Feat/customer planning details actions section
  src/components/Balance/BalanceContainer.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/ActionCards.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/CustomerPlanningActions.columns.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/CustomerPlanningActionsTable.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/CustomerPlanningTypeColumn.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/PlanningActionResume.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/components/ActionCards/ActionCards.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/components/ActionCards/index.ts
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/components/index.ts
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTable.columns.tsx
  src/modules/wallet/pages/WalletScreen/components/Balance.tsx
  src/styles/theme/components/button.ts
  src/types/index.ts
Labels: Feature

#70 Fix requests and metrics in customer planning details
  src/components/StatCard/StatCard.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/CustomerPlanningActionsTable.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/PlanningActionResume.tsx
Labels: Fix

#69 Finish integrating some table values
  src/api/customer/endpoints.ts
  src/api/customer/types.ts
  src/components/Header/Header.tsx
  src/modules/customers/pages/CustomerDetailScreen/CustomerDetailScreen.tsx
  src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPlanningTable.columns.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.columns.tsx
  src/types/global.d.ts
Labels: Feature

#71 Creates PlanningHistoryHeader
  src/components/PlanningHistory/PlanningHistory.tsx
  src/components/PlanningHistory/components/ActionStepper/ActionStepper.tsx
  src/components/PlanningHistory/components/ActionStepper/index.ts
  src/components/PlanningHistory/components/index.ts
  src/components/PlanningHistory/index.ts
  src/components/icons/ArrowRight.tsx
  src/components/index.ts
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/CustomerPlanningActionsTable.tsx
  src/styles/theme/foundations/colors.ts
  src/styles/theme/foundations/semanticTokens.ts
Labels: Feature

#38 Feature/receipts
  package.json
  src/components/AbsoluteNextImage/AbsoluteNextImage.tsx
  src/components/AbsoluteNextImage/index.ts
  src/components/CustomAcordion/CustomAcordion.tsx
  src/components/CustomAcordion/index.ts
  src/components/Sidebar/Sidebar.tsx
  src/components/TextInput/TextInput.tsx
  src/components/icons/Close2.tsx
  src/components/icons/Minus2.tsx
  src/components/icons/index.ts
  src/components/index.ts
  src/modules/receipts/pages/ReceiptsScreen/ReceiptsScreen.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/ActionDetails/ActionDetails.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/ActionDetails/ActionDetailsItem.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/ActionDetails/index.ts
  src/modules/receipts/pages/ReceiptsScreen/components/Cell/Cell.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/Cell/index.ts
  src/modules/receipts/pages/ReceiptsScreen/components/DescribeYourExpense/DescribeYourExpense.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/DescribeYourExpense/index.ts
  src/modules/receipts/pages/ReceiptsScreen/components/DrawerExpenseReceipt/DrawerExpenseReceipt.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/DrawerExpenseReceipt/index.ts
  src/modules/receipts/pages/ReceiptsScreen/components/FinalizedTables/FinalizedTables.columns.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/FinalizedTables/FinalizedTables.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/FinalizedTables/index.ts
  src/modules/receipts/pages/ReceiptsScreen/components/Header/Header.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/Header/index.ts
  src/modules/receipts/pages/ReceiptsScreen/components/ImageCarousel/CarouselCard.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/ImageCarousel/ImageCarousel.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/ImageCarousel/ModalCarouselCard.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/ImageCarousel/index.ts
  src/modules/receipts/pages/ReceiptsScreen/components/ProveYourExpenses/ProveYourExpenses.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/ProveYourExpenses/index.ts
  src/modules/receipts/pages/ReceiptsScreen/components/ReceiptStatus/ReceiptStatus.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/ReceiptStatus/index.ts
  src/modules/receipts/pages/ReceiptsScreen/components/RunningTable/RunningTable.columns.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/RunningTable/RunningTable.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/RunningTable/index.ts
  src/modules/receipts/pages/ReceiptsScreen/components/Segment/Segment.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/Segment/index.ts
  src/modules/receipts/pages/ReceiptsScreen/components/TableFilter/TableFilter.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/TableFilter/index.ts
  src/modules/receipts/pages/ReceiptsScreen/components/ViewButton/ViewButton.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/ViewButton/index.ts
  src/modules/receipts/pages/ReceiptsScreen/components/index.ts
  src/modules/receipts/pages/ReceiptsScreen/stores/index.ts
  src/modules/receipts/pages/ReceiptsScreen/stores/useDrawerExpenseReceipt.ts
  src/styles/theme/components/input.ts
  src/styles/theme/foundations/colors.ts
  src/styles/theme/foundations/semanticTokens.ts
  src/styles/theme/foundations/textStyles.ts
Labels: Feature

#72 Feat/integration drawer create planning action
  package.json
  src/api/planning/mutations/useCreatePlanning.ts
  src/components/DatePicker/DatePicker.tsx
  src/components/DatePicker/DatePickerHeader.tsx
  src/components/DatePicker/index.ts
  src/components/index.ts
  src/modules/planning/api/endpoints.ts
  src/modules/planning/api/index.ts
  src/modules/planning/api/mutations/index.ts
  src/modules/planning/api/mutations/useCreatePlanningAction.ts
  src/modules/planning/api/types.ts
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/CreatePlanningActionDrawerButton.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/PlanningActionForm.schema.ts
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/PlanningActionFormAccordion.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/SelectDateSection.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTable.tsx
  src/styles/theme/externals/index.ts
  src/styles/theme/externals/react-datepicker.ts
  src/styles/theme/foundations/shadows.ts
  src/styles/theme/globalStyles.ts
  src/utils/brlToCents.ts
  src/utils/brlToNumber.ts
  src/utils/index.ts
  yarn.lock
Labels: Feature

#73 fix: all project and change brand color
  public/assets/icons/EditIcon.svg
  public/assets/icons/ExpandIcon.svg
  public/assets/icons/EyeOpenIcon.svg
  public/assets/icons/MinusIcon.svg
  public/assets/icons/TrashIcon.svg
  public/assets/images/bayer-logo.webp
  public/assets/images/intacta-logo.webp
  src/components/PlatformLogo/PlatformLogo.tsx
  src/components/PlatformLogo/index.ts
  src/components/Sidebar/Sidebar.tsx
  src/components/icons/EditIcon.tsx
  src/components/icons/EyeOpenIcon.tsx
  src/components/icons/TrashIcon.tsx
  src/components/icons/index.ts
  src/components/index.ts
  src/modules/auth/pages/LoginScreen/LoginScreen.tsx
  src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPlanningStatusColumn.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTableStatusColumn.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionTypeColumn.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTable.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningStatusColumn.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTable.columns.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTableAction.tsx
  src/modules/wallet/pages/WalletScreen/WalletScreen.tsx
  src/modules/wallet/pages/WalletScreen/components/Balance.tsx
  src/modules/wallet/pages/WalletScreen/components/WalletBalance/WalletBalance.tsx
  src/modules/wallet/pages/WalletScreen/components/WalletBalance/index.ts
  src/modules/wallet/pages/WalletScreen/components/index.ts
  src/styles/theme/components/button.ts
  src/styles/theme/foundations/colors.ts
  src/styles/theme/foundations/semanticTokens.ts
  src/types/index.ts
  src/utils/centsToCompactValue.ts
  src/utils/getTotalPlanningBudgetValue.ts
Labels: Fix

#65 Feature/file input
  package.json
  src/components/icons/Upload.tsx
  src/components/icons/index.ts
  src/modules/receipts/components/CardImageViewing/CardImageViewing.tsx
  src/modules/receipts/components/CardImageViewing/index.ts
  src/modules/receipts/components/ImageListing/ImageListing.tsx
  src/modules/receipts/components/ImageListing/index.ts
  src/modules/receipts/components/MultipleFileInput/MultipleFileInput.tsx
  src/modules/receipts/components/MultipleFileInput/index.ts
  src/modules/receipts/components/index.ts
  src/styles/theme/components/index.ts
  src/styles/theme/components/scrollbarStyle.ts
  src/styles/theme/externals/index.ts
  src/styles/theme/externals/multipleFileInputStyles.ts
  yarn.lock
Labels: Feature

#77 fix: dates in planning and planning action
  src/api/planning/types.ts
  src/components/DatePicker/DatePicker.tsx
  src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPlanningTable.columns.tsx
  src/modules/planning/api/types.ts
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/CreatePlanningActionDrawerButton.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/PlanningActionForm.schema.ts
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/SelectDateSection.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTable.columns.tsx
  src/styles/theme/externals/react-datepicker.ts
  src/types/global.d.ts
Labels: Fix

#78 feat: view action details drawer
  public/assets/icons/ExpandIcon.svg
  public/assets/icons/MinusIcon.svg
  public/assets/images/bayer-logo.webp
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTable.columns.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTableAction.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/ViewActionDetailsDrawer/ViewActionDetailsDrawer.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/ViewActionDetailsDrawer/index.ts
  src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTableAction.tsx
  src/styles/theme/foundations/layerStyles.ts
Labels: Feature

#79 Feat/history planning get history
  src/api/planning/endpoints.ts
  src/api/planning/queries/index.ts
  src/api/planning/queries/useGetPlanningHistoric.ts
  src/api/planning/types.ts
  src/components/PlanningHistoric/PlanningHistoric.tsx
  src/components/PlanningHistoric/components/Historic/Historic.tsx
  src/components/PlanningHistoric/components/Historic/HistoricItem.tsx
  src/components/PlanningHistoric/components/Historic/HistoricItemSummary.tsx
  src/components/PlanningHistoric/components/Historic/HistoricItemTable.tsx
  src/components/PlanningHistoric/components/Historic/HistoricItemTableRow.tsx
  src/components/PlanningHistoric/components/Historic/index.ts
  src/components/PlanningHistoric/components/HistoricStepper/HistoricStepper.tsx
  src/components/PlanningHistoric/components/HistoricStepper/index.ts
  src/components/PlanningHistoric/components/index.ts
  src/components/PlanningHistoric/index.ts
  src/components/PlanningHistory/PlanningHistory.tsx
  src/components/PlanningHistory/components/ActionStepper/index.ts
  src/components/PlanningHistory/components/PlanningDetail/PlanningDetail.tsx
  src/components/PlanningHistory/components/PlanningDetail/index.ts
  src/components/PlanningHistory/components/index.ts
  src/components/PlanningHistory/index.ts
  src/components/index.ts
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/CustomerPlanningActionsTable.tsx
  src/styles/theme/foundations/colors.ts
  src/types/global.d.ts
Labels: Feature

#81 feat: planning status section
  src/api/planning/endpoints.ts
  src/api/planning/queries/index.ts
  src/api/planning/queries/useGetPlanningStatus.ts
  src/api/planning/types.ts
  src/components/DatePicker/DatePicker.tsx
  src/middleware.ts
  src/modules/planning/pages/CreatePlanningScreen/CreatePlanningScreen.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionSection/CreatePlanningActionSection.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionSection/index.ts
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningBalance/CreatePlanningBalance.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningStatusSection/CreatePlanningStatusSection.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningStatusSection/index.ts
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTable.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/index.ts
  src/pages/planejamento/criar-novo-planejamento/index.tsx
  src/styles/theme/components/badge.ts
  src/styles/theme/components/input.ts
  src/styles/theme/components/scrollbarStyle.ts
Labels: Feature

#83 Feat/historic approval
  src/components/PlanningHistoricDrawer/PlanningHistoricDrawer.tsx
  src/components/PlanningHistoricDrawer/components/Historic/Historic.tsx
  src/components/PlanningHistoricDrawer/components/PlanningValidator/PlanningValidator.tsx
  src/components/PlanningHistoricDrawer/components/PlanningValidator/components/ReasonInput/ReasonInput.tsx
  src/components/PlanningHistoricDrawer/components/PlanningValidator/components/ReasonInput/index.ts
  src/components/PlanningHistoricDrawer/components/PlanningValidator/components/ValidatorTable/ValidatorTable.columns.tsx
  src/components/PlanningHistoricDrawer/components/PlanningValidator/components/ValidatorTable/ValidatorTable.tsx
  src/components/PlanningHistoricDrawer/components/PlanningValidator/components/ValidatorTable/index.ts
  src/components/PlanningHistoricDrawer/components/PlanningValidator/components/index.ts
  src/components/PlanningHistoricDrawer/components/PlanningValidator/index.ts
  src/components/PlanningHistoricDrawer/components/index.ts
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/CustomerPlanningActionsTable.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/PlanningActionResume.tsx
  src/styles/theme/foundations/colors.ts
Labels: Feature

#84 Creates mutation to update historic
  src/api/planning/endpoints.ts
  src/api/planning/mutations/index.ts
  src/api/planning/mutations/useUpdatePlanningHistoric.ts
  src/api/planning/types.ts
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/PlanningActionResume.tsx
Labels: Feature

#85 Feat/planning historic drawer
  public/assets/icons/ArrowCircleDown.svg
  public/assets/icons/Arrow_Minimal_Up 2.svg
  public/assets/icons/ClockRegularIcon.svg
  public/assets/icons/EditIcon.svg
  public/assets/icons/ExpandIcon.svg
  public/assets/icons/EyeOpenIcon.svg
  public/assets/icons/MinusIcon.svg
  public/assets/icons/PhoneIcon.svg
  public/assets/icons/TrashIcon.svg
  src/components/DynamicTable/DynamicTable.tsx
  src/components/Historic/HistoricAccordion.tsx
  src/components/Historic/HistoricCancelButton.tsx
  src/components/Historic/HistoricContainer.tsx
  src/components/Historic/HistoricDoneButton.tsx
  src/components/Historic/HistoricFooter.tsx
  src/components/Historic/HistoricHeader.tsx
  src/components/Historic/HistoricMessage.tsx
  src/components/Historic/HistoricPlanningActionRow.tsx
  src/components/Historic/HistoricTable.columns.tsx
  src/components/Historic/HistoricTable.tsx
  src/components/Historic/HistoricTextInput.tsx
  src/components/Historic/HistoricTitle.tsx
  src/components/Historic/index.ts
  src/components/PlanningHistoricDrawer/PlanningHistoricDrawer.tsx
  src/components/PlanningHistoricDrawer/PlanningHistoricStatus.tsx
  src/components/PlanningHistoricDrawer/PlanningHistoricStep.tsx
  src/components/PlanningHistoricDrawer/components/Historic/Historic.tsx
  src/components/PlanningHistoricDrawer/components/Historic/HistoricItem.tsx
  src/components/PlanningHistoricDrawer/components/Historic/HistoricItemSummary.tsx
  src/components/PlanningHistoricDrawer/components/Historic/HistoricItemTable.tsx
  src/components/PlanningHistoricDrawer/components/Historic/HistoricItemTableRow.tsx
  src/components/PlanningHistoricDrawer/components/Historic/index.ts
  src/components/PlanningHistoricDrawer/components/HistoricStepper/HistoricStepper.tsx
  src/components/PlanningHistoricDrawer/components/HistoricStepper/index.ts
  src/components/PlanningHistoricDrawer/components/PlanningValidator/PlanningValidator.tsx
  src/components/PlanningHistoricDrawer/components/PlanningValidator/components/ReasonInput/ReasonInput.tsx
  src/components/PlanningHistoricDrawer/components/PlanningValidator/components/ReasonInput/index.ts
  src/components/PlanningHistoricDrawer/components/PlanningValidator/components/ValidatorTable/ValidatorTable.tsx
  src/components/PlanningHistoricDrawer/components/PlanningValidator/components/ValidatorTable/index.ts
  src/components/PlanningHistoricDrawer/components/PlanningValidator/components/index.ts
  src/components/PlanningHistoricDrawer/components/PlanningValidator/index.ts
  src/components/PlanningHistoricDrawer/components/index.ts
  src/components/icons/ClockRegularIcon.tsx
  src/components/icons/index.ts
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningStatusSection/CreatePlanningStatusSection.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsStatistics/PlanningActionsStatistics.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/ActionDetails/ActionDetailsItem.tsx
  src/styles/theme/components/button.ts
  src/styles/theme/components/stepper.ts
  src/styles/theme/foundations/colors.ts
  src/styles/theme/foundations/semanticTokens.ts
  src/styles/theme/foundations/shadows.ts
  src/types/index.ts
Labels: Feature

#88 Creates enxoval page
  src/components/Sidebar/Sidebar.items.tsx
  src/components/icons/Package.tsx
  src/components/icons/PackageSmall.tsx
  src/components/icons/index.ts
  src/modules/index.ts
  src/modules/trousseau/index.ts
  src/modules/trousseau/pages/TrousseauScreen.tsx
  src/modules/trousseau/pages/index.ts
  src/pages/enxoval/index.tsx
Labels: Feature

#89 Makes request to get all actions
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerHistoricDrawer/CustomerHistoricDrawer.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/CustomerPlanningActionsTable.tsx
Labels: Feature

#91 Finish supplier section
  src/components/icons/EmailIcon.tsx
  src/components/icons/PhoneIcon.tsx
  src/modules/trousseau/pages/TrousseauScreen.tsx
  src/modules/trousseau/pages/TrousseauScreen/TrousseauScreen.tsx
  src/modules/trousseau/pages/TrousseauScreen/components/SuppliersSection/SupplierCard.tsx
  src/modules/trousseau/pages/TrousseauScreen/components/SuppliersSection/SuppliersSection.tsx
  src/modules/trousseau/pages/TrousseauScreen/components/SuppliersSection/index.ts
  src/modules/trousseau/pages/TrousseauScreen/components/index.ts
  src/modules/trousseau/pages/TrousseauScreen/index.ts
  src/styles/theme/components/badge.ts
  src/styles/theme/foundations/colors.ts
Labels: Feature

#90 feat: planning historic drawer and past planning historic steps
  src/api/planning/endpoints.ts
  src/api/planning/types.ts
  src/components/DynamicTable/DynamicTable.tsx
  src/components/Historic/HistoricAccordionContainer.tsx
  src/components/Historic/HistoricFooter.tsx
  src/components/Historic/HistoricHeader.tsx
  src/components/Historic/HistoricMessage.tsx
  src/components/Historic/HistoricPlanningActionRow.tsx
  src/components/Historic/HistoricTable.tsx
  src/components/Historic/HistoricTextInput.tsx
  src/components/Historic/HistoricTitleFarmer.tsx
  src/components/Historic/HistoricTitleManager.tsx
  src/components/Historic/index.ts
  src/components/PastPlanningHistoricSteps/PastPlanningHistoricSteps.tsx
  src/components/PastPlanningHistoricSteps/PastPlanningHistoricTitle.tsx
  src/components/PastPlanningHistoricSteps/index.ts
  src/components/index.ts
  src/hooks/usePagination.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerHistoricDrawer/CustomerHistoricDrawer.tsx
  src/modules/planning/pages/CreatePlanningScreen/CreatePlanningScreen.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionSection/CreatePlanningActionSection.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningStatusSection/CreatePlanningStatusSection.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningStatusSection/CreatePlanningStatusSectionSkeleton.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningStatusSection/index.ts
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningHistoricDrawer/PlanningHistoricDrawer.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningHistoricDrawer/SendPlanningFormStep.schema.ts
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningHistoricDrawer/SendPlanningFormStep.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningHistoricDrawer/index.ts
  src/styles/theme/components/stepper.ts
  src/styles/theme/foundations/textStyles.ts
  src/types/global.d.ts
Labels: Feature

#92 Feat/historic drawer status
  public/assets/icons/ClockRegularIcon.svg
  src/components/HistoricDrawer/HistoricDrawerHeader.tsx
  src/components/HistoricDrawer/HistoricDrawerStatus.tsx
  src/components/icons/ArrowRightMediumIcon.tsx
  src/lib/axios.ts
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionSection/CreatePlanningActionSection.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningStatusSection/CreatePlanningStatusSection.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningHistoricDrawer/PlanningHistoricDrawer.tsx
Labels: Feature

#94 Feat/modal dispatch component
  public/assets/icons/WarningIcon.svg
  src/components/ConfirmationModal/ConfirmationModal.tsx
  src/components/ConfirmationModal/index.ts
  src/components/PastPlanningHistoricSteps/PastPlanningHistoricSteps.tsx
  src/components/PastPlanningHistoricSteps/PastPlanningHistoricTitle.tsx
  src/components/icons/WarningIcon.tsx
  src/components/icons/index.ts
  src/components/index.ts
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTableAction.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTableAction.tsx
  src/modules/trousseau/pages/TrousseauScreen/components/TrousseauOptionsSection/TrousseauDownloadOption.tsx
  src/styles/theme/components/button.ts
  src/styles/theme/components/modal.ts
Labels: Feature

#95 Adds swiper slider
  package.json
  src/modules/trousseau/pages/TrousseauScreen/components/TrousseauOptionsSection/TrousseauOptionsSection.tsx
  yarn.lock
Labels: Feature

#97 feat: hover click in row tables and delete mutations
  src/api/planning/endpoints.ts
  src/api/planning/mutations/index.ts
  src/api/planning/mutations/useCreatePlanning.ts
  src/api/planning/mutations/useDeletePlanning.ts
  src/api/planning/mutations/useUpdatePlanningHistoric.ts
  src/api/planning/types.ts
  src/modules/planning/api/endpoints.ts
  src/modules/planning/api/mutations/index.ts
  src/modules/planning/api/mutations/useCreatePlanningAction.ts
  src/modules/planning/api/mutations/useDeletePlanningAction.ts
  src/modules/planning/api/types.ts
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTable.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTableAction.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTable.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTableAction.tsx
Labels: Feature

#96 Creates results section
  src/modules/simulator/pages/SimulatorScreen/SimulatorScreen.tsx
  src/modules/simulator/pages/SimulatorScreen/components/ResultsSection/ResultCard.tsx
  src/modules/simulator/pages/SimulatorScreen/components/ResultsSection/ResultsSection.tsx
  src/modules/simulator/pages/SimulatorScreen/components/ResultsSection/index.ts
  src/modules/simulator/pages/SimulatorScreen/components/index.ts
  src/styles/theme/foundations/colors.ts
Labels: Feature

#98 Fix customer table values
  src/api/customer/endpoints.ts
  src/api/customer/types.ts
  src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.columns.tsx
  src/types/global.d.ts
Labels: Feature

#101 feat: trousseau list in create planning action
  public/assets/images/enxoval1.png
  public/assets/images/enxoval2.png
  public/assets/images/enxoval3.png
  public/assets/images/enxoval4.png
  src/components/Trousseau/TrousseauContainer.tsx
  src/components/Trousseau/TrousseauImage.tsx
  src/components/Trousseau/TrousseauLabel.tsx
  src/components/Trousseau/TrousseauSlider.tsx
  src/components/Trousseau/index.ts
  src/components/index.ts
  src/config/index.ts
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/CreatePlanningActionDrawerButton.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/PlanningActionFormAccordion.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/RecommendationsAccordion.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/TrousseauSelectAccordion.tsx
  src/modules/trousseau/pages/TrousseauScreen/components/TrousseauOptionsSection/TrousseauImage.tsx
  src/modules/trousseau/pages/TrousseauScreen/components/TrousseauOptionsSection/TrousseauImageCard.tsx
  src/modules/trousseau/pages/TrousseauScreen/components/TrousseauOptionsSection/TrousseauOptionsSection.tsx
  src/styles/theme/components/checkbox.ts
  src/types/global.d.ts
Labels: Feature

#100 Feat/simulator page oportunity table
  src/modules/simulator/pages/SimulatorScreen/SimulatorScreen.tsx
  src/modules/simulator/pages/SimulatorScreen/components/FinancialOportunitySection/FinancialOportunitySection.tsx
  src/modules/simulator/pages/SimulatorScreen/components/FinancialOportunitySection/FinancialOportunityTable.columns.tsx
  src/modules/simulator/pages/SimulatorScreen/components/FinancialOportunitySection/FinancialOportunityTable.tsx
  src/modules/simulator/pages/SimulatorScreen/components/FinancialOportunitySection/index.ts
  src/modules/simulator/pages/SimulatorScreen/components/HarverstSection/HarvestInformationItem.tsx
  src/modules/simulator/pages/SimulatorScreen/components/HarverstSection/HarvestSection.tsx
  src/modules/simulator/pages/SimulatorScreen/components/HarverstSection/HarvestSwitch.tsx
  src/modules/simulator/pages/SimulatorScreen/components/HarverstSection/Pipe.tsx
  src/modules/simulator/pages/SimulatorScreen/components/HarverstSection/index.ts
  src/modules/simulator/pages/SimulatorScreen/components/MinimumNumbersSection/MinimumNumbersTable.columns.tsx
  src/modules/simulator/pages/SimulatorScreen/components/index.ts
  src/styles/theme/foundations/colors.ts
Labels: Feature

#102 WIP Feat/simulator page harvest section
  src/modules/simulator/pages/SimulatorScreen/components/HarverstSection/HarvestSection.tsx
  src/modules/simulator/pages/SimulatorScreen/components/HarverstSection/HarvestSlider.tsx
  src/modules/simulator/pages/SimulatorScreen/components/HarverstSection/HarvestSwitch.tsx
Labels: Feature, WIP

#103 feat: UpdatePlanningActionDrawer component to edit and create mode
  src/modules/planning/api/endpoints.ts
  src/modules/planning/api/mutations/index.ts
  src/modules/planning/api/mutations/useUpdatePlanningAction.ts
  src/modules/planning/api/types.ts
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/CreatePlanningActionDrawerButton.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTableAction.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/UpdatePlanningActionDrawer/AccordionIcon.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/UpdatePlanningActionDrawer/PlanningActionForm.schema.ts
  src/modules/planning/pages/CreatePlanningScreen/components/UpdatePlanningActionDrawer/PlanningActionFormAccordion.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/UpdatePlanningActionDrawer/PlanningActionFormStepper.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/UpdatePlanningActionDrawer/RecommendationsAccordion.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/UpdatePlanningActionDrawer/SelectDateSection.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/UpdatePlanningActionDrawer/TrousseauSelectAccordion.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/UpdatePlanningActionDrawer/UpdatePlanningActionDrawer.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/UpdatePlanningActionDrawer/index.ts
  src/modules/planning/pages/CreatePlanningScreen/stores/index.ts
  src/modules/planning/pages/CreatePlanningScreen/stores/useUpdatePlanningActionStore.ts
Labels: Feature

#107 feat: dashboard cards
  public/assets/icons/WarningIcon.svg
  src/components/Sidebar/MenuItemSkeleton.tsx
  src/components/Sidebar/Sidebar.items.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/StatCard/StatCard.tsx
  src/components/icons/index.ts
  src/middleware.ts
  src/modules/dashboard/pages/DashboardScreen/DashboardScreen.tsx
Labels: Feature

#105 Creates kanban page
  src/components/Sidebar/Sidebar.items.tsx
  src/modules/KanbanScreen/KanbanScreen.tsx
  src/modules/KanbanScreen/index.ts
  src/modules/index.ts
  src/pages/planejamento/index.tsx
Labels: Feature

#106 Feat/kanban page card
  src/modules/planning/pages/KanbanScreen/KanbanScreen.tsx
  src/modules/planning/pages/KanbanScreen/components/KanbanCard.tsx
  src/modules/planning/pages/KanbanScreen/components/index.ts
  src/styles/theme/components/badge.ts
  src/styles/theme/foundations/semanticTokens.ts
Labels: Feature

#111 Feat/trousseau page api
  public/assets/images/enxoval1.png
  public/assets/images/enxoval2.png
  public/assets/images/enxoval3.png
  public/assets/images/enxoval4.png
  src/api/index.ts
  src/api/trousseau/endpoints.ts
  src/api/trousseau/index.ts
  src/api/trousseau/queries/index.ts
  src/api/trousseau/queries/useGetTrousseau.tsx
  src/api/trousseau/types.ts
  src/components/Trousseau/TrousseauSlider.tsx
  src/components/Trousseau/TrousseauSliderSkeleton.tsx
  src/components/Trousseau/index.ts
  src/config/index.ts
  src/modules/planning/pages/CreatePlanningScreen/components/UpdatePlanningActionDrawer/TrousseauSelectAccordion.tsx
  src/modules/trousseau/pages/TrousseauScreen/components/TrousseauOptionsSection/TrousseauCatalogOption.tsx
  src/modules/trousseau/pages/TrousseauScreen/components/TrousseauOptionsSection/TrousseauCatalogSkeleton.tsx
  src/modules/trousseau/pages/TrousseauScreen/components/TrousseauOptionsSection/TrousseauDownloadOption.tsx
  src/modules/trousseau/pages/TrousseauScreen/components/TrousseauOptionsSection/TrousseauOptionsSection.tsx
  src/types/global.d.ts
Labels: Feature

#112 fix: all project bad codes
  src/api/planning/mutations/useUpdatePlanningHistoric.ts
  src/api/planning/types.ts
  src/components/Historic/HistoricAccordion.tsx
  src/components/Historic/HistoricDoneButton.tsx
  src/components/Historic/HistoricHeader.tsx
  src/components/Historic/HistoricTitleManager.tsx
  src/components/HistoricDrawer/HistoricDrawerStep.tsx
  src/components/PastPlanningHistoricSteps/PastPlanningHistoricSteps.tsx
  src/components/PastPlanningHistoricSteps/PastPlanningHistoricTitle.tsx
  src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPendingPlanningNotification.tsx
  src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPlanningTable.columns.tsx
  src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPlanningTable.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/CustomerPlanningActions.columns.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/CustomerPlanningActionsTable.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.tsx
  src/modules/planning/pages/CreatePlanningScreen/CreatePlanningScreen.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTable.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningHistoricDrawer/SendPlanningFormStep.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTable.tsx
  src/styles/theme/components/tooltip.ts
  src/types/index.ts
Labels: Fix

#113 feat: added toast to all mutations
  src/api/auth/mutations/useLoginMutation.ts
  src/api/auth/mutations/useUpdateUser.ts
  src/api/planning/mutations/useCreatePlanning.ts
  src/api/planning/mutations/useDeletePlanning.ts
  src/api/planning/mutations/useUpdatePlanningHistoric.ts
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerHistoricDrawer/CustomerHistoricDrawer.tsx
  src/modules/planning/api/mutations/useCreatePlanningAction.ts
  src/modules/planning/api/mutations/useDeletePlanningAction.ts
  src/modules/planning/api/mutations/useUpdatePlanningAction.ts
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningHistoricDrawer/SendPlanningFormStep.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningStatisticsSection/PlanningStatisticsSection.tsx
Labels: Feature

#114 Feat/simulator page api
  src/components/Header/Header.tsx
  src/components/TextInput/TextInput.tsx
  src/components/icons/ComputerBig.tsx
  src/components/icons/index.ts
  src/modules/simulator/pages/SimulatorScreen/components/FinancialOpportunitySection/FinancialOpportunityTable.columns.tsx
  src/modules/simulator/pages/SimulatorScreen/components/FinancialOpportunitySection/FinancialOpportunityTable.tsx
  src/modules/simulator/pages/SimulatorScreen/components/HarvestSection/HarvestInformationItem.tsx
  src/modules/simulator/pages/SimulatorScreen/components/HarvestSection/HarvestSection.tsx
  src/modules/simulator/pages/SimulatorScreen/components/HarvestSection/HarvestSlider.tsx
  src/modules/simulator/pages/SimulatorScreen/components/HarvestSection/HarvestSwitch.tsx
  src/modules/simulator/pages/SimulatorScreen/components/MinimumNumbersSection/MinimumNumbersTable.columns.tsx
  src/modules/simulator/pages/SimulatorScreen/components/MinimumNumbersSection/MinimumNumbersTable.tsx
  src/modules/simulator/pages/SimulatorScreen/components/ResultsSection/ResultsSection.tsx
  src/modules/simulator/pages/SimulatorScreen/stores/index.ts
  src/modules/simulator/pages/SimulatorScreen/stores/useSimulatorStore.tsx
  src/modules/simulator/pages/SimulatorScreen/utils/index.ts
  src/pages/simulador/index.tsx
  src/utils/formatValue.ts
  src/utils/index.ts
  src/utils/mask.ts
  src/utils/numberToCompactValue.ts
Labels: Feature

#115 fix: step icon from historic status
  public/assets/icons/ChartIcon.svg
  public/assets/icons/RejectedIcon.svg
  public/assets/icons/SmallDoneIcon.svg
  src/components/Historic/HistoricTitleManager.tsx
  src/components/PastPlanningHistoricSteps/PastPlanningHistoricSteps.tsx
  src/components/icons/RejectedIcon.tsx
  src/components/icons/SmallDoneIcon.tsx
  src/components/icons/index.ts
Labels: Fix

#116 Integrates supplier with API
  src/api/trousseau/endpoints.ts
  src/modules/trousseau/pages/TrousseauScreen/TrousseauScreen.tsx
  src/modules/trousseau/pages/TrousseauScreen/components/SuppliersSection/SupplierCard.tsx
  src/modules/trousseau/pages/TrousseauScreen/components/SuppliersSection/SuppliersSection.tsx
  src/modules/trousseau/pages/TrousseauScreen/components/SuppliersSection/SuppliersSectionSkeleton.tsx
  src/modules/trousseau/pages/TrousseauScreen/components/TrousseauOptionsSection/TrousseauOptionsSection.tsx
  src/types/global.d.ts
Labels: Feature

#117 fix: user update response and status loading in planning actions
  src/api/auth/mutations/useUpdateUser.ts
  src/api/auth/types.ts
  src/components/CustomToast/CustomToast.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsStatistics/PlanningActionsStatistics.tsx
  src/styles/theme/foundations/semanticTokens.ts
  src/types/global.d.ts
Labels: Fix

#118 Fix/hide rtv planning buttons
  src/components/Header/Header.tsx
  src/modules/customers/pages/CustomerDetailScreen/CustomerDetailScreen.tsx
  src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPlanningTable.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/CustomerPlanningActions.columns.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/CustomerPlanningActionsTable.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/PlanningActionResume.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningDetailCards/CustomerPlanningDetailCards.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerCards/CustomerCards.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.tsx
Labels: Feature

#110 Feature/pdv receipt integration
  src/modules/api/endpoints.ts
  src/modules/api/index.ts
  src/modules/api/queries/index.ts
  src/modules/api/queries/useGetActions.ts
  src/modules/api/types.ts
  src/modules/receipts/pages/ReceiptsScreen/ReceiptsScreen.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/ActionDetails/ActionDetails.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/ActionDetails/ActionDetailsItem.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/ActionDetails/typesInPortuguese.ts
  src/modules/receipts/pages/ReceiptsScreen/components/FinalizedTables/FinalizedTables.columns.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/FinalizedTables/FinalizedTables.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/RunningTable/RunningTable.columns.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/RunningTable/RunningTable.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/Segment/Segment.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/TableFilter/TableFilter.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/ViewButton/ViewButton.tsx
  src/modules/receipts/pages/ReceiptsScreen/stores/index.ts
  src/modules/receipts/pages/ReceiptsScreen/stores/useActionStore.ts
  src/pages/comprovantes/index.tsx
Labels: Feature

#124 Fix see planning button
  src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPendingPlanningNotification.tsx
  src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPlanningTable.tsx
  src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/utils/index.ts
  src/types/global.d.ts
Labels: Feature

#125 Integrates customer filter with api
  src/components/filters/CustomerFilter/CustomerFilter.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.tsx
Labels: Feature

#127 Fix text styles from version 1.0.1
  src/components/Balance/BalanceExpirationDate.tsx
  src/modules/auth/pages/OnboardingScreen/OnboardingScreen.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.columns.tsx
  src/modules/receipts/pages/ProducerProofsScreen/ProducerProofsScreen.tsx
  src/modules/simulator/pages/SimulatorScreen/components/HarvestSection/HarvestSwitch.tsx
Labels: Feature

#128 Feat/creates user profile drawer
  src/components/Header/Header.tsx
  src/components/Header/components/UserMenu/UserMenu.tsx
  src/components/Header/components/UserMenu/index.tsx
  src/components/Header/components/UserProfile/UserProfile.tsx
  src/components/Header/components/UserProfile/index.ts
  src/components/Header/components/index.ts
  src/components/icons/Close.tsx
  src/components/icons/Person.tsx
  src/components/index.ts
Labels: Feature

#129 Feat/creates user profile design
  src/components/Header/Header.tsx
  src/components/Header/components/UserProfile/UserProfile.tsx
  src/components/Header/components/UserProfile/index.ts
  src/components/Header/components/index.ts
  src/components/UserProfileDrawer/UserProfileDrawer.tsx
  src/components/UserProfileDrawer/components/ProfileDetails/ProfileDetails.tsx
  src/components/UserProfileDrawer/components/ProfileDetails/ProfileImage.tsx
  src/components/UserProfileDrawer/components/ProfileDetails/ProfileInformationField.tsx
  src/components/UserProfileDrawer/components/ProfileDetails/ProfileInformationFieldContainer.tsx
  src/components/UserProfileDrawer/components/ProfileDetails/index.ts
  src/components/UserProfileDrawer/components/ProfileDrawer/ProfileDrawerBody.tsx
  src/components/UserProfileDrawer/components/ProfileDrawer/ProfileDrawerFooter.tsx
  src/components/UserProfileDrawer/components/ProfileDrawer/ProfileDrawerHeader.tsx
  src/components/UserProfileDrawer/components/ProfileDrawer/index.ts
  src/components/UserProfileDrawer/components/index.ts
  src/components/UserProfileDrawer/index.ts
  src/components/index.ts
  src/lib/next-auth/providers/credentials.ts
  src/types/global.d.ts
  src/types/next-auth.d.ts
Labels: Feature

#130 Creates query to get pending plannings
  src/api/planning/endpoints.ts
  src/api/planning/queries/index.ts
  src/api/planning/queries/useGetFarmerPendingPlannings.ts
  src/api/planning/types.ts
  src/components/Balance/BalanceContainer.tsx
  src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPendingPlanningNotification.tsx
  src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPlanningTable.tsx
Labels: Fix

#131 Feat/create edit profile
  src/components/Avatar/Avatar.tsx
  src/components/UserProfileDrawer/UserProfileDrawer.tsx
  src/components/UserProfileDrawer/components/EditProfileForm/EditProfileForm.tsx
  src/components/UserProfileDrawer/components/EditProfileForm/ProfileForm.tsx
  src/components/UserProfileDrawer/components/EditProfileForm/index.ts
  src/components/UserProfileDrawer/components/ProfileDetails/ProfileDetails.tsx
  src/components/UserProfileDrawer/components/ProfileDetails/ProfileImage.tsx
  src/components/UserProfileDrawer/components/ProfileDetails/ProfileInformationField.tsx
  src/components/UserProfileDrawer/components/ProfileImage.tsx
  src/components/UserProfileDrawer/components/index.ts
  src/components/icons/EditIcon.tsx
  src/components/icons/House.tsx
  src/components/icons/index.ts
  src/styles/theme/components/button.ts
Labels: Feature

#132 Creates util to invalidate queries, invalidaes queries on mutation
  src/api/planning/mutations/useUpdatePlanningHistoric.ts
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningHistoricDrawer/SendPlanningFormStep.tsx
  src/utils/index.ts
  src/utils/invalidateQueries.ts
Labels: Fix

#133 Feat/create safra filter
  src/components/filters/HarvestFilter/HarvestFilter.tsx
  src/components/filters/HarvestFilter/index.ts
  src/components/filters/index.ts
  src/modules/receipts/pages/ProducerProofsScreen/ProducerProofsScreen.tsx
Labels: Feature

#134 Creates resource filter
  src/components/filters/ResourceFilter/ResourceFilter.tsx
  src/components/filters/ResourceFilter/index.ts
  src/components/filters/index.ts
  src/modules/receipts/pages/ProducerProofsScreen/ProducerProofsScreen.tsx
Labels: Feature

#136 Fix undefined values error in rtv
  src/components/Balance/BalanceContainer.tsx
  src/components/filters/CustomerFilter/CustomerFilter.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.columns.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/RunningTable/RunningTable.columns.tsx
Labels: Feature

#137 feat: error screens
  public/assets/icons/ChevronCircleRightIcon.svg
  public/assets/icons/RejectedIcon.svg
  public/assets/icons/SmallDoneIcon.svg
  public/assets/images/internal-error.svg
  public/assets/images/notfound.svg
  src/components/icons/ChevronCircleRightIcon.tsx
  src/components/icons/index.ts
  src/layouts/LayoutCustomError.tsx
  src/layouts/index.ts
  src/modules/errors/index.ts
  src/modules/errors/pages/ClientErrorScreen/ClientErrorScreen.tsx
  src/modules/errors/pages/ClientErrorScreen/index.ts
  src/modules/errors/pages/InternalErrorScreen/InternalErrorScreen.tsx
  src/modules/errors/pages/InternalErrorScreen/index.ts
  src/modules/errors/pages/NotFoundScreen/NotFoundScreen.tsx
  src/modules/errors/pages/NotFoundScreen/index.ts
  src/modules/errors/pages/index.ts
  src/modules/index.ts
  src/pages/404.tsx
  src/pages/500.tsx
  src/pages/_document.tsx
  src/pages/_error.tsx
  src/styles/theme/foundations/colors.ts
  src/styles/theme/foundations/layerStyles.ts
  src/styles/theme/foundations/semanticTokens.ts
  src/styles/theme/foundations/shadows.ts
Labels: Feature

#138 feat: drawer to list notifications
  src/api/auth/mutations/useLoginMutation.ts
  src/components/NotificationBar/HeaderNotificationBar.tsx
  src/components/NotificationBar/NotificationBar.tsx
  src/components/NotificationBar/NotificationCard.tsx
  src/components/NotificationBar/NotificationsDrawer.tsx
  src/components/NotificationBar/components/index.ts
  src/middleware.ts
  src/styles/theme/components/drawer.ts
Labels: Feature

#139 fix: update user response
  src/api/auth/endpoints.ts
  src/api/auth/types.ts
  src/api/harverst/endpoints.ts
  src/api/harverst/index.ts
  src/api/index.ts
  src/api/planning/endpoints.ts
  src/api/planning/types.ts
  src/components/Balance/BalanceContainer.tsx
  src/components/UserProfileDrawer/components/ProfileDetails/ProfileDetails.tsx
  src/components/filters/CustomerFilter/CustomerFilter.tsx
  src/lib/next-auth/providers/credentials.ts
  src/modules/auth/pages/RegisterScreen/components/RegisterFormTabs/RegisterFormTabs.tsx
  src/modules/customers/pages/CustomerDetailScreen/CustomerDetailScreen.tsx
  src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningDetailCards/CustomerPlanningDetailCards.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningBalance/PlanningBalance.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTable.tsx
  src/modules/receipts/pages/ProducerProofsScreen/components/StockTable/StockTable.columns.tsx
  src/modules/receipts/pages/ReceiptsScreen/components/FinalizedTables/FinalizedTables.columns.tsx
  src/types/global.d.ts
  src/types/next-auth.d.ts
Labels: Fix

#142 fix: requests create planning and delete actions
  src/api/auth/endpoints.ts
  src/api/harverst/endpoints.ts
  src/api/harverst/index.ts
  src/api/harverst/types.ts
  src/api/planning/endpoints.ts
  src/components/Header/components/UserMenu/UserMenu.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.tsx
  src/modules/planning/api/endpoints.ts
  src/modules/planning/api/mutations/useCreatePlanningAction.ts
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningBalance/CreatePlanningBalance.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningStatusSection/CreatePlanningStatusSection.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/UpdatePlanningActionDrawer/UpdatePlanningActionDrawer.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningBalance/PlanningBalance.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTable.tsx
  src/types/global.d.ts
  src/types/next-auth.d.ts
Labels: Fix

#143 feat: warning modal and custom erros
  src/api/planning/mutations/useCreatePlanning.ts
  src/api/types.ts
  src/components/WarningModal/WarningModal.tsx
  src/components/WarningModal/index.ts
  src/components/index.ts
  src/lib/axios.ts
  src/lib/next-auth/providers/credentials.ts
  src/modules/planning/pages/CreatePlanningScreen/CreatePlanningScreen.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningBalance/CreatePlanningBalance.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTable.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningHistoricDrawer/SendPlanningFormStep.tsx
  src/modules/planning/pages/PlanningScreen/components/CreatePlanningButton/CreatePlanningButton.tsx
  src/modules/planning/pages/PlanningScreen/components/CreatePlanningButton/index.ts
  src/modules/planning/pages/PlanningScreen/components/PlanningBalance/PlanningBalance.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTable.tsx
Labels: Feature

#140 Feat/integrate edit form api
  src/api/auth/endpoints.ts
  src/api/auth/mutations/index.ts
  src/api/auth/types.ts
  src/api/farmer/endpoints.ts
  src/api/farmer/index.ts
  src/api/farmer/mutations/index.ts
  src/api/farmer/mutations/useUpdateFarmer.ts
  src/api/farmer/types.ts
  src/api/manager/endpoints.ts
  src/api/manager/index.ts
  src/api/manager/mutations/index.ts
  src/api/manager/mutations/useUpdateManager.ts
  src/api/manager/types.ts
  src/components/UserProfileDrawer/UserProfileDrawer.tsx
  src/components/UserProfileDrawer/components/EditProfileForm/EditProfileForm.schemas.ts
  src/components/UserProfileDrawer/components/EditProfileForm/EditProfileForm.tsx
  src/components/UserProfileDrawer/components/EditProfileForm/ProfileForm.tsx
  src/components/UserProfileDrawer/components/ProfileDetails/ProfileDetails.tsx
  src/components/UserProfileDrawer/components/ProfileDetails/ProfileInformationField.tsx
  src/components/UserProfileDrawer/components/ProfileDrawer/ProfileDrawerBody.tsx
  src/components/UserProfileDrawer/components/ProfileDrawer/ProfileDrawerFooter.tsx
  src/components/UserProfileDrawer/components/ProfileDrawer/index.ts
  src/components/filters/CustomerFilter/CustomerFilter.tsx
  src/modules/auth/pages/RegisterScreen/components/RegisterFormTabs/RegisterFormTabs.tsx
  src/modules/planning/pages/KanbanScreen/components/KanbanSection/KanbanCard.tsx
  src/types/global.d.ts
Labels: Feature

#145 Fix queries and mutations
  src/api/auth/endpoints.ts
  src/api/customer/endpoints.ts
  src/api/customer/types.ts
  src/api/farmer/endpoints.ts
  src/api/manager/endpoints.ts
  src/api/manager/types.ts
  src/api/planning/endpoints.ts
  src/api/planning/types.ts
  src/components/Balance/BalanceContainer.tsx
  src/modules/customers/pages/CustomerDetailScreen/CustomerDetailScreen.tsx
  src/modules/customers/pages/CustomerDetailScreen/components/CustomerStatisticsSection/CustomerStatisticsSection.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerCards/CustomerCards.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.tsx
  src/modules/planning/pages/KanbanScreen/KanbanScreen.tsx
  src/modules/planning/pages/PlanningScreen/components/CreatePlanningButton/CreatePlanningButton.tsx
  src/modules/planning/pages/PlanningScreen/components/PlanningStatisticsSection/PlanningStatisticsSection.tsx
  src/modules/wallet/pages/WalletScreen/components/WalletBalance/WalletBalance.tsx
  src/types/global.d.ts
Labels: Fix

#150 feat: harvest section integrate with api in receipts
  src/api/auth/endpoints.ts
  src/api/farmer/mutations/useUpdateFarmer.ts
  src/api/harvest/endpoints.ts
  src/api/harvest/index.ts
  src/api/harvest/queries/index.ts
  src/api/harvest/queries/useGetHarvests.ts
  src/api/harvest/types.ts
  src/api/index.ts
  src/modules/receipts/pages/ReceiptsScreenFarmer/components/CurrentHarvestSection/CurrentHarvestSection.tsx
Labels: Feature
