Repository loomi-dev/bayer-geracao-demanda-client, pull requests merged in 2024-01, with the labels that each got.

#152 feat: user notifications
  src/api/index.ts
  src/api/notifications/endpoints.ts
  src/api/notifications/index.ts
  src/api/notifications/queries/index.ts
  src/api/notifications/queries/useGetNotificationsByUser.ts
  src/api/notifications/types.ts
  src/components/NotificationBar/NotificationBar.tsx
  src/components/NotificationBar/NotificationCard.tsx
  src/components/NotificationBar/NotificationCardSkeleton.tsx
  src/components/NotificationBar/NotificationsDrawer.tsx
  src/types/global.d.ts
Labels: Feature

#151 Feat/create receipts summary
  src/api/receipts/endpoints.ts
  src/api/receipts/queries/index.ts
  src/api/receipts/queries/useGetReceiptsSummary.ts
  src/api/receipts/types.ts
  src/modules/receipts/pages/ReceiptsScreenFarmer/components/ReceiptsSummarySection/ReceiptsSummarySection.tsx
Labels: Feature

#153 refactor: drawer receipts
  src/modules/receipts/components/ImageCarousel/CarouselCard.tsx
  src/modules/receipts/components/ImageCarousel/ImageCarousel.tsx
  src/modules/receipts/components/ImageCarousel/ModalCarouselCard.tsx
  src/modules/receipts/components/ImageCarousel/index.ts
  src/modules/receipts/components/ReceiptStatus/ReceiptStatus.tsx
  src/modules/receipts/components/SendReceiptsButton/SendReceiptsButton.tsx
  src/modules/receipts/components/SendReceiptsButton/index.ts
  src/modules/receipts/components/SendReceiptsDrawer/SendReceiptsDrawer.tsx
  src/modules/receipts/components/SendReceiptsDrawer/SendReceiptsFormAccordion.schema.ts
  src/modules/receipts/components/SendReceiptsDrawer/SendReceiptsFormAccordion.tsx
  src/modules/receipts/components/SendReceiptsDrawer/index.ts
  src/modules/receipts/components/ViewReceiptsButton/ViewReceiptsButton.tsx
  src/modules/receipts/components/ViewReceiptsButton/index.ts
  src/modules/receipts/components/ViewReceiptsDrawer/ExpenseDetail.tsx
  src/modules/receipts/components/ViewReceiptsDrawer/ReceiptFilesAccordion.tsx
  src/modules/receipts/components/ViewReceiptsDrawer/ViewReceiptsDrawer.tsx
  src/modules/receipts/components/ViewReceiptsDrawer/index.ts
  src/modules/receipts/components/index.ts
  src/modules/receipts/pages/ReceiptsScreenFarmer/components/DrawerSendProofAction/index.ts
  src/modules/receipts/pages/ReceiptsScreenFarmer/components/ReceiptsActionsTable/ProveActionButton.tsx
  src/modules/receipts/pages/ReceiptsScreenFarmer/components/ReceiptsActionsTable/ReceiptsActionsTable.columns.tsx
  src/modules/receipts/pages/ReceiptsScreenFarmer/components/ReceiptsActionsTable/ReceiptsActionsTable.tsx
  src/modules/receipts/pages/ReceiptsScreenFarmer/components/index.ts
  src/modules/receipts/pages/ReceiptsScreenManager/components/DescribeYourExpense/index.ts
  src/modules/receipts/pages/ReceiptsScreenManager/components/FinalizedTables/FinalizedTables.columns.tsx
  src/modules/receipts/pages/ReceiptsScreenManager/components/ProveYourExpenses/index.ts
  src/modules/receipts/pages/ReceiptsScreenManager/components/ReceiptActionsDetailsDrawer/index.ts
  src/modules/receipts/pages/ReceiptsScreenManager/components/RunningTable/RunningTable.columns.tsx
  src/modules/receipts/pages/ReceiptsScreenManager/components/ViewReceiptActionsDetailsButton/ViewReceiptActionsDetailsButton.tsx
  src/modules/receipts/pages/ReceiptsScreenManager/components/ViewReceiptActionsDetailsButton/index.ts
  src/modules/receipts/pages/ReceiptsScreenManager/components/index.ts
Labels: Refactor

#154 Feat/integrate multipliers filter
  src/api/customer/endpoints.ts
  src/api/customer/types.ts
  src/api/farmer/endpoints.ts
  src/api/farmer/queries/index.ts
  src/api/farmer/queries/useGetFarmers.ts
  src/api/farmer/types.ts
  src/api/receipts/endpoints.ts
  src/api/receipts/types.ts
  src/components/BaseFilter/components/FilterOption.tsx
  src/components/filters/CustomerFilter/CustomerFilter.tsx
  src/components/filters/Filter/Filter.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.tsx
  src/modules/planning/pages/KanbanScreen/KanbanScreen.tsx
  src/modules/receipts/pages/ReceiptsScreenFarmer/components/ReceiptsActionsTable/ReceiptsActionsTable.tsx
  src/modules/receipts/pages/ReceiptsScreenManager/ReceiptsScreenManager.tsx
Labels: Feature

#155 Feat/integrate search filter
  src/api/receipts/endpoints.ts
  src/api/receipts/types.ts
  src/components/filters/SearchFilter/index.tsx
  src/components/filters/index.ts
  src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.tsx
  src/modules/planning/pages/KanbanScreen/KanbanScreen.tsx
  src/modules/receipts/pages/ReceiptsScreenManager/ReceiptsScreenManager.tsx
Labels: Feature

#156 Feat/integrate region filter
  src/api/customer/endpoints.ts
  src/api/customer/types.ts
  src/api/receipts/endpoints.ts
  src/api/receipts/types.ts
  src/components/filters/RegionFilter/RegionFilter.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.tsx
  src/modules/planning/pages/KanbanScreen/KanbanScreen.tsx
  src/modules/receipts/pages/ReceiptsScreenManager/ReceiptsScreenManager.tsx
Labels: Feature

#163 feat: infinite scroll notifications
  src/components/NotificationBar/NotificationsDrawer.tsx
  src/hooks/index.ts
  src/hooks/useInfiniteScroll.tsx
Labels: Feature

#164 Finishes integrating harvest filter
  src/api/customer/endpoints.ts
  src/api/customer/types.ts
  src/api/receipts/endpoints.ts
  src/api/receipts/types.ts
  src/components/filters/HarvestFilter/HarvestFilter.tsx
  src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.tsx
  src/modules/receipts/pages/ReceiptsScreenFarmer/ReceiptsScreenFarmer.tsx
  src/modules/receipts/pages/ReceiptsScreenFarmer/components/ReceiptsActionsTable/ReceiptsActionsTable.tsx
  src/modules/receipts/pages/ReceiptsScreenFarmer/components/ReceiptsSummarySection/ReceiptsSummarySection.tsx
Labels: Feature

#166 Feat/redefines dashboard layout
  src/modules/dashboard/pages/DashboardScreen/DashboardScreen.tsx
  src/modules/dashboard/pages/DashboardScreen/components/ActionsResumeSection/ActionsResumeSection.tsx
  src/modules/dashboard/pages/DashboardScreen/components/ActionsResumeSection/index.ts
  src/modules/dashboard/pages/DashboardScreen/components/FinancialSection/FinancialCard.tsx
  src/modules/dashboard/pages/DashboardScreen/components/FinancialSection/FinancialSection.tsx
  src/modules/dashboard/pages/DashboardScreen/components/FinancialSection/index.ts
  src/modules/dashboard/pages/DashboardScreen/components/index.ts
Labels: Feature

#167 Feat/integrates new dashboard with api
  src/api/manager/endpoints.ts
  src/api/manager/queries/index.ts
  src/api/manager/queries/useGetDashboard.ts
  src/api/manager/types.ts
  src/components/filters/ActionFilter/ActionFilter.tsx
  src/modules/dashboard/pages/DashboardScreen/DashboardScreen.tsx
  src/modules/dashboard/pages/DashboardScreen/components/ActionsResumeSection/ActionsResumeSection.tsx
  src/modules/dashboard/pages/DashboardScreen/components/FinancialSection/FinancialCard.tsx
  src/modules/dashboard/pages/DashboardScreen/components/FinancialSection/FinancialSection.tsx
Labels: Feature

#169 Fix getTrousseau filter query
  src/api/trousseau/endpoints.ts
  src/api/trousseau/types.ts
  src/modules/trousseau/pages/TrousseauScreen/TrousseauScreen.tsx
  src/modules/trousseau/pages/TrousseauScreen/components/SuppliersSection/SuppliersSection.tsx
  src/modules/trousseau/pages/TrousseauScreen/components/SuppliersSection/SuppliersSectionZeroState.tsx
Labels: Fix

#171 Creates another warning modal
  src/api/types.ts
  src/components/WarningModal/WarningModal.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningHistoricDrawer/SendPlanningFormStep.tsx
  src/modules/planning/pages/PlanningScreen/components/CreatePlanningButton/CreatePlanningButton.tsx
Labels: Fix

#172 Creates warning modal for create and edit actions error
  src/components/WarningModal/WarningModal.tsx
  src/modules/planning/pages/CreatePlanningScreen/components/UpdatePlanningActionDrawer/UpdatePlanningActionDrawer.tsx
Labels: Feature

#170 Feat/refresh token
  src/api/auth/endpoints.ts
  src/api/auth/types.ts
  src/api/farmer/mutations/useUpdateFarmer.ts
  src/api/farmer/types.ts
  src/api/manager/mutations/useUpdateManager.ts
  src/api/manager/types.ts
  src/lib/axios.ts
  src/lib/next-auth/authOptions.ts
  src/lib/next-auth/providers/credentials.ts
  src/modules/errors/pages/ClientErrorScreen/ClientErrorScreen.tsx
  src/types/next-auth.d.ts
Labels: Feature

#173 Feat/loading login
  src/components/index.ts
  src/components/motions/index.ts
  src/components/motions/motions.ts
  src/modules/auth/pages/OnboardingScreen/OnboardingScreen.tsx
  src/pages/_app.tsx
  src/pages/bem-vindo/index.tsx
  src/pages/comprovantes/index.tsx
  src/pages/planejamento/index.tsx
Labels: Feature

#176 Feat/integration forgot password api
  public/assets/favicon.webp
  public/assets/images/logo.webp
  src/api/auth/endpoints.ts
  src/api/auth/mutations/index.ts
  src/api/auth/mutations/useForgotPassword.ts
  src/api/auth/mutations/useResetPassword.ts
  src/api/auth/types.ts
  src/api/types.ts
  src/modules/auth/pages/ForgotPasswordScreen/ForgotPasswordScreen.tsx
  src/modules/auth/pages/ForgotPasswordScreen/components/ForgotPasswordFormSteps/ForgotPasswordFormSteps.tsx
  src/modules/auth/pages/ForgotPasswordScreen/components/PasswordResetSuccess/PasswordResetSuccess.tsx
  src/modules/auth/pages/ForgotPasswordScreen/components/ResetPasswordForm/ResetPasswordForm.tsx
  src/modules/auth/pages/ForgotPasswordScreen/components/SendEmailForm/SendEmailForm.schema.ts
  src/modules/auth/pages/ForgotPasswordScreen/components/SendEmailForm/SendEmailForm.tsx
  src/modules/auth/pages/ForgotPasswordScreen/stores/index.ts
  src/modules/auth/pages/ForgotPasswordScreen/stores/useForgotPasswordStore.ts
  src/pages/_document.tsx
  src/styles/theme/components/button.ts
Labels: Feature

#178 feat: styles container notifications
  src/components/NotificationBar/NotificationBar.tsx
Labels: Feature

#181 feat: added planning actions in notification card
  public/assets/icons/GrouperIcon.svg
  src/api/notifications/endpoints.ts
  src/components/NotificationBar/NotificationBar.tsx
  src/components/NotificationBar/NotificationCard.tsx
  src/components/NotificationBar/NotificationGrouper.tsx
  src/components/NotificationBar/NotificationPlanningAction.tsx
  src/components/NotificationBar/NotificationsDrawer.tsx
  src/components/icons/GrouperIcon.tsx
  src/components/icons/index.ts
  src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTable.tsx
  src/types/global.d.ts
Labels: Feature
